#!/bin/bash

# Bail if the media share isn't available
if ! ~/uberzach/isMediaMounted; then
        exit 0
fi

# Run a search for each monitored series
~/uberzach/torrentMonitored.pl null | xargs -n 1 -0 ~/uberzach/findTorrent.pl
