#!/bin/bash

# Bail if the media share isn't available
if ! /home/bjames/uberzach/isMediaMounted; then
        exit 0
fi

# Run a search for each monitored series
/home/bjames/uberzach/torrentMonitored.pl null | xargs -n 1 -0 /home/bjames/uberzach/findTorrent.pl | /home/bjames/uberzach/download.scpt
