#!/bin/bash 
BLOCKLIST_DIR=/home/bjames/.config/transmission-daemon/blocklists
wget -q -O- http://www.bluetack.co.uk/config/level{1,2,3}.gz | \
gunzip -c > ${BLOCKLIST_DIR}/level123 && \
/etc/init.d/transmission-daemon reload
